Veewee::Session.declare({
  :cpu_count => '2',
  :memory_size=> '512',
  :disk_size => '10140',
  :disk_format => 'VDI',
  :hostiocache => 'off',
  :os_type_id => 'RedHat_64',
  :iso_file => "Mageia/mga2-boot-nonfree.iso",
  :iso_src => "http://mirror.aarnet.edu.au/pub/xxxx.iso",
  :iso_md5 => "0274423b95aed09b53286b5fc7282fef",
  :iso_download_timeout => 1000,
  :boot_wait => "5",
  :boot_cmd_sequence => [ 'linux automatic=met:http,netw:dhcp,hos:veewee,ser:10.0.0.4,dir:mga2/x86_64, kickstart=http://%IP%:%PORT%/auto_inst.cfg<Enter>' ],
  :kickstart_port => "7122",
  :kickstart_timeout => 10000,
  :kickstart_file => "auto_inst.cfg",
  :ssh_login_timeout => "10000",
  :ssh_user => "vagrant",
  :ssh_password => "vagrant",
  :ssh_key => "",
  :ssh_host_port => "7222",
  :ssh_guest_port => "22",
  :sudo_cmd => "echo '%p'|sudo -S sh '%f'",
  :shutdown_cmd => "/sbin/halt -h -p",
  :postinstall_files => [ "postinstall.sh"],
  :postinstall_timeout => 10000
})
